# Generated by Django 4.0.2 on 2022-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0002_remove_tag_goal_goal_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tag',
        ),
        migrations.AddField(
            model_name='goal',
            name='tags',
            field=models.CharField(blank=True, choices=[('physical', 'Physical'), ('spiritual', 'Spiritual'), ('work', 'Work')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
