# Generated by Django 4.0.2 on 2022-02-07 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0004_rename_tactit_week_tactic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='score',
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twelveWeekYear_app.tactic')),
            ],
        ),
    ]
