# Generated by Django 4.0.2 on 2022-02-07 08:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0005_remove_week_score_dailyscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reflection', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Reflection on the day!')),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('tactic', models.ManyToManyField(to='twelveWeekYear_app.Tactic')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twelveWeekYear_app.week')),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='tactic',
        ),
        migrations.RemoveField(
            model_name='day',
            name='twelve_week',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.DeleteModel(
            name='DailyScore',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
