# Generated by Django 4.0.2 on 2022-02-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0006_dailyreflection_remove_day_tactic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='status',
            field=models.CharField(choices=[['in progress', 'In Progress'], ['not started', 'Not Started'], ['completed', 'Completed']], default='not started', max_length=150),
        ),
    ]
