# Generated by Django 4.0.2 on 2022-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0007_tactic_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
    ]
