# Generated by Django 4.0.2 on 2022-02-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0008_rename_end_date_goal_due_date_remove_goal_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twelveweek',
            name='end_date',
        ),
    ]
