# Generated by Django 4.0.2 on 2022-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twelveWeekYear_app', '0009_remove_twelveweek_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreflection',
            name='tactic',
            field=models.ManyToManyField(blank=True, to='twelveWeekYear_app.Tactic'),
        ),
    ]
